# Generated by Django 2.2.5 on 2019-09-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.TextField(max_length=350),
        ),
        migrations.CreateModel(
            name='Playtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_day', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('N', 'Night')], default='N', max_length=1)),
                ('Videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Videogame')),
            ],
        ),
    ]
