# Generated by Django 2.2.5 on 2019-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190916_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playtime',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='playtime',
            name='date',
            field=models.DateField(verbose_name='play date'),
        ),
    ]
