# Generated by Django 2.2.5 on 2019-09-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190916_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
            ],
        ),
    ]
