# Generated by Django 2.2.5 on 2019-09-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190916_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='consoles',
            field=models.ManyToManyField(to='main_app.Console'),
        ),
    ]
