# Generated by Django 2.2.5 on 2019-09-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_videogame_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Videogame')),
            ],
        ),
    ]
